services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-app
    volumes:
      - .server:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://root:root@db:3306/mybank_db?charset=utf8mb4"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: mybank_db 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
